# Generated by Django 4.2.7 on 2024-03-24 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_category_name_en_us_category_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='name_en_us',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='name_ru',
        ),
    ]
